'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property id As String
    Public Property ssn As String
    Public Property lastname As String
    Public Property firstname As String
    Public Property add1 As String
    Public Property add2 As String
    Public Property city As String
    Public Property state As String
    Public Property zip As String
    Public Property phone As String
    Public Property deptcode As String
    Public Property hiredate As Nullable(Of Date)
    Public Property jobcode As String
    Public Property comment As String
    Public ReadOnly Property FullName As String
        Get
            Return firstname & " " & lastname
        End Get
    End Property

End Class
